#!/usr/bin/env python3

import sys
import os

# Add the current directory to sys.path so we can import queuectl_core
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from queuectl_core.cli import main

if __name__ == '__main__':
    main()
